name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release Please

    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json

  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Parse Version
        id: version
        run: echo "version=$(echo "${{ needs.release-please.outputs.tag_name }}" | cut -c 2-)" >> "$GITHUB_OUTPUT"

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Latest Changelog
        run: npx changelogithub --output LATEST_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          version: PlayerBehaviorRecord-${{ steps.version.outputs.version }}

          modrinth-id: ciA0JPWg
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            build/libs/PlayerBehaviorRecord-${{ steps.version.outputs.version }}.jar
          changelog-file: LATEST_CHANGELOG.md

          loaders: |
            fabric
          game-version-filter: releases
